name: soundswap
description: "A Flutter Windows desktop app for replacing video audio in batches."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  archive: ^4.0.7
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  path: ^1.9.1
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf
        - asset: assets/fonts/Battambang-Bold.ttf
          weight: 700
    - family: Hanuman
      fonts:
        - asset: assets/fonts/Hanuman-Regular.ttf
        - asset: assets/fonts/Hanuman-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: KhmerOS
      fonts:
        - asset: assets/fonts/KhmerOS.ttf
    - family: Khmer OS Siemreap
      fonts:
        - asset: "assets/fonts/KhmerOSSiemreap.ttf"
    - family: .Mondulkiri U h
      fonts:
        - asset: "assets/fonts/mond40uhgs.ttf"
    - family: KunKhmer
      fonts:
        - asset: "assets/fonts/KunKhmer.ttf"
    - family: AKbalthom Chamnap Chhun
      fonts:
        - asset: "assets/fonts/AKbalthom Chamnap Chhun Version 1.10.ttf"
    - family: AKbalthom Choeung Ek
      fonts:
        - asset: "assets/fonts/AKbalthom Choeung Ek.ttf"
